(*

  This file is automatically generated by OCamlEditor 1.13.1, do not edit.

*)

open Printf

let packages = [
  (** datasource *)
  "datasource","\
version         = \"1.0.0\"
description     = \"Datasource management and connection pooling.\"
requires        = \"\"
archive(byte)   = \"datasource.cma\"
archive(native) = \"datasource.cmxa\"

package \"pg\" (
  version         = \"1.0.0\"
  description     = \"Fast PostgreSQL driver based on PG'OCaml.\"
  requires        = \"calendar,datasource\"
  archive(byte)   = \"pgdatasource.cma\"
  archive(native) = \"pgdatasource.cmxa\"
)",
  [
    "datasource.cma";
    "datasource.cmxa";
    "pgdatasource.cma";
    "pgdatasource.cmxa"
  ], [
    "tests.cmi";
    "pool.cmi";
    "datasourceUtil.cmi";
    "fastPGOCaml-0.4.cmi";
    "fastPGOCaml.cmi";
    "datasource.cmi";
    "pg_escape.cmi";
    "postgreSQL.cmi";
    "S3.cmi";
    "test.cmi"
  ], [
    "pool.mli";
    "fastPGOCaml.mli";
    "datasource.mli";
    "postgreSQL.mli"
  ];
]

let _ = 
  if Array.length Sys.argv < 2 then failwith "Invalid parameters";
  let cwd = Sys.getcwd() in
  Sys.chdir "src";
  let lib_ext = if Sys.win32 then ".lib" else ".a" in
  List.iter begin fun (name, defs, archives, (cmis : string list), (mlis : string list)) ->
    let cmxas = List.filter (fun x -> Filename.check_suffix x ".cmxa") archives in
    let libs = String.concat " " (List.map (fun x -> (Filename.chop_extension x) ^ lib_ext) cmxas) in
    let arcs = String.concat " " archives in
    let cmis = String.concat " " cmis in
    let mlis = String.concat " " mlis in
    let _META = "META" in
    if Sys.file_exists _META then failwith "Cannot write META file: file exists";
    let chan = open_out_bin _META in
    try
      let sudo = if Sys.win32 || List.mem Sys.argv.(1) ["print"] then "" else "sudo -E " in
      let cmd = ref [] in
      if not (List.mem Sys.argv.(1) ["install"; "uninstall"; "reinstall"; "print"]) then failwith "Invalid parameters";
      output_string chan defs;
      flush chan;
      if List.mem Sys.argv.(1) ["uninstall"; "reinstall"] then cmd := (sprintf "%socamlfind remove %s" sudo name) :: !cmd;
      if List.mem Sys.argv.(1) ["install"; "reinstall"; "print"] then 
        cmd := (sprintf "%socamlfind install %s %s %s %s %s %s" sudo name _META arcs libs cmis mlis) :: !cmd;
      assert (!cmd <> []);
      let cmd = String.concat " && " (List.rev !cmd) in
      if List.mem Sys.argv.(1) ["print"] then printf "\n##### %s.%s #####\n\n%s\n\n# %s\n%!" _META name defs cmd;
      let exit_code = if Sys.argv.(1) = "print" then 0 else Sys.command cmd in
      if exit_code <> 0 then eprintf "Error: command %s exited with code %d\n%!" cmd exit_code;
      if Sys.file_exists _META then (close_out_noerr chan; Sys.remove _META)
    with ex -> begin
      if Sys.file_exists _META then (close_out_noerr chan; Sys.remove _META)
    end
  end packages;
  Sys.chdir cwd;
